export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";
export const ADD_TO_CART_RESET = "ADD_TO_CART_RESET";
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";

export const GET_CARTITEMS_REQUEST = "GET_CARTITEMS_REQUEST";
export const GET_CARTITEMS_SUCCESS = "GET_CARTITEMS_SUCCESS";
export const GET_CARTITEMS_FAIL = "GET_CARTITEMS_FAIL";

export const UPDATE_CART_ITEM_FAIL = "UPDATE_CART_ITEM_FAIL";
export const UPDATE_CART_ITEM_RESET = "UPDATE_CART_ITEM_RESET";
export const UPDATE_CART_ITEM_REQUEST = "UPDATE_CART_ITEM_REQUEST";
export const UPDATE_CART_ITEM_SUCCESS = "UPDATE_CART_ITEM_SUCCESS";

export const REMOVE_CART_ITEM_REQUEST = "REMOVE_CART_ITEM_REQUEST";
export const REMOVE_CART_ITEM_SUCCESS = "REMOVE_CART_ITEM_SUCCESS";
export const REMOVE_CART_ITEM_FAIL = "REMOVE_CART_ITEM_FAIL";
export const REMOVE_CART_ITEM_RESET = "REMOVE_CART_ITEM_RESET";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPIG_INFO";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
